### ISSUE TITLE
Failed to load module "canberra-gtk-module" using MIPI CSI Camera

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [otamajakusi/dockerfile-yolov5-jetson#3]
Hi @otamajakusi, thank you for this amazing repo. I am using an imx219 mipi csi camera connected to /dev/video0 on the Jetson Nano and when running the command **run.sh** everything runs properly and as expected except that I cannot view my camera feed and all I see is a green screen. The results of running the command **./run.sh** is as follows:

```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', nosave=False, project='runs/detect', save_conf=False, save_txt=False, source='0', update=False, view_img=False, weights='yolov5s.pt')
YOLOv5 \U0001f680 v5.0-14-g238583b torch 1.8.0 CUDA:0 (NVIDIA Tegra X1, 3956.1328125MB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt to yolov5s.pt...
100%|######################################| 14.1M/14.1M [00:12<00:00, 1.20MB/s]

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPS
Gtk-Message: 02:13:00.303: Failed to load module "canberra-gtk-module"
[ WARN:0] global /tmp/pip-build-3fcriusp/opencv-python/opencv/modules/videoio/src/cap_v4l.cpp (1914) getProperty VIDEOIO(V4L2:/dev/video0): Unable to get camera FPS
1/1: 0...  success (3264x2464 at 99.00 FPS).

0: 512x640 Done. (2.845s)
0: 512x640 Done. (0.174s)
0: 512x640 Done. (0.173s)
```

Is there anyway I could solve this issue?

Thank you & Best Regards,
Abu

**Comment by otamajakusi** [comment]
Hi @abuelgasimsaadeldin, thank you for the reporting, but I think this is not a docker problem. This problem seems to be CSI on Jetson platform problem. Anyway I'd like to solve this problem. Thanks.

**Comment by otamajakusi** [comment]
see https://github.com/JetsonHacksNano/CSI-Camera
```bash
$ python3 simple_camera.py
```
works fine on the **host** environment, but doesn't work on the container environment.
GStreamer seems to be supported on the host environment, but does not on the container environment.
Opencv build seems to be required on the container environment.

**Comment by techaitr** [comment]
how do opencv build on the container environment?

**Comment by otamajakusi** [comment]
77c133ad646b917ca0c48260a668a816b10b9702 supports CSI camera.
But please make sure yolov5 with CSI camera requires yolov5 modification like this:
```patch
diff --git a/utils/datasets.py b/utils/datasets.py
index 43e4e59..14fa5c9 100755
--- a/utils/datasets.py
+++ b/utils/datasets.py
@@ -280,7 +280,35 @@ class LoadStreams:  # multiple IP or RTSP cameras
                 import pafy
                 s = pafy.new(s).getbest(preftype="mp4").url  # YouTube URL
             s = eval(s) if s.isnumeric() else s  # i.e. s = '0' local webcam
-            cap = cv2.VideoCapture(s)
+
+            def gstreamer_pipeline(
+                capture_width=1280,
+                capture_height=720,
+                display_width=1280,
+                display_height=720,
+                framerate=60,
+                flip_method=0,
+            ):
+                return (
+                    "nvarguscamerasrc ! "
+                    "video/x-raw(memory:NVMM), "
+                    "width=(int)%d, height=(int)%d, "
+                    "format=(string)NV12, framerate=(fraction)%d/1 ! "
+                    "nvvidconv flip-method=%d ! "
+                    "video/x-raw, width=(int)%d, height=(int)%d, format=(string)BGRx ! "
+                    "videoconvert ! "
+                    "video/x-raw, format=(string)BGR ! appsink"
+                    % (
+                        capture_width,
+                        capture_height,
+                        framerate,
+                        flip_method,
+                        display_width,
+                        display_height,
+                    )
+                )
+
+            cap = cv2.VideoCapture(gstreamer_pipeline(flip_method=0), cv2.CAP_GSTREAMER)
             assert cap.isOpened(), f'Failed to open {s}'
             w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
             h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

```

**Comment by abuelgasimsaadeldin** [comment]
Awesome! thanks allot, will test it out soon.

**Comment by abuelgasimsaadeldin** [comment]
Hi @otamajakusi, I have just tested out the new Dockerfile with CSI Camera support. I built the Dockerfile and made the changes as mentioned above to *datasets.py* as shown in my image below:

![2](https://user-images.githubusercontent.com/68045710/117253858-47df6d00-ae7a-11eb-8e74-38711fcc166e.jpg)
 
I then proceeded to mount the new folder "utils" which is located locally (with the changes made to datasets.py) to the docker container using the "--volume" command (I verified in the container that the datasets.py had been updated successfully).

Finally when trying to run the "run.sh" script, I ran into the following error message: 

```
Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
Gtk-Message: 06:44:03.233: Failed to load module "canberra-gtk-module"

(test:1): GStreamer-WARNING **: 06:44:03.459: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
(Argus) Error FileOperationFailed: Connecting to nvargus-daemon failed: No such file or directory (in src/rpc/socket/client/SocketClientDispatch.cpp, function openSocketConnection(), line 201)
(Argus) Error FileOperationFailed: Cannot create camera provider (in src/rpc/socket/client/SocketClientDispatch.cpp, function createCameraProvider(), line 102)
Error generated. /dvs/git/dirty/git-master_linux/multimedia/nvgstreamer/gst-nvarguscamera/gstnvarguscamerasrc.cpp, execute:639 Failed to create CameraProvider

(test:1): GStreamer-CRITICAL **: 06:44:09.303: gst_mini_object_set_qdata: assertion 'object != NULL' failed
[ WARN:0] global /tmp/pip-req-build-bn4gnwkh/opencv/modules/videoio/src/cap_gstreamer.cpp (1081) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
1/1: 0...  success (1280x720 at 60.00 FPS).

Traceback (most recent call last):
  File "detect.py", line 183, in <module>
    detect(opt=opt)
  File "detect.py", line 52, in detect
    dataset = LoadStreams(source, img_size=imgsz, stride=stride)
  File "/yolov5/utils/datasets.py", line 325, in _init_
    s = np.stack([letterbox(x, self.img_size, stride=self.stride)[0].shape for x in self.imgs], 0)  # shapes
  File "/yolov5/utils/datasets.py", line 325, in <listcomp>
    s = np.stack([letterbox(x, self.img_size, stride=self.stride)[0].shape for x in self.imgs], 0)  # shapes
  File "/yolov5/utils/datasets.py", line 852, in letterbox
    shape = img.shape[:2]  # current shape [height, width]
AttributeError: 'NoneType' object has no attribute 'shape'
```

Your help in solving this issue would be highly appreciated.

best,
Abu

**Comment by otamajakusi** [comment]
@abuelgasimsaadeldin 
Sorry for the lack of comments, but `-v /tmp/argus_socket:/tmp/argus_socket` is required to use CSI camera (=gstreamer support) for docker run command.
Please check `run-csi-camera.sh`

**Comment by abuelgasimsaadeldin** [comment]
Hi @otamajakusi, sorry my bad for not realizing that, it worked great after adding ```-v /tmp/argus_socket:/tmp/argus_socket```. Thanks!
